openapi: 3.0.1
info:
  title: AsyncCallbackDemoAPI
  description: API Definition of AsyncCallbackDemoAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/asyncdemo
- url: https://localhost:8253/asyncdemo
paths:
  /orders:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /callback:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
